trigger:
- '*'
pool:
  name: 'MyAgentPool' 
  
variables: 
  group: 'Release'
steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.x'
  inputs:
    packageType: sdk
    version: '8.x'
    includePreviewVersions: true
          
- task: DotNetCoreCLI@2
  displayName: 'Build step'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  condition: false
  displayName: 'Publish step'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: CopyFiles@2
  condition: false
  displayName: 'Copy Terraform files to artifacts'
  inputs:
    SourceFolder: Terraform
    TargetFolder: '$(build.artifactstagingdirectory)/Terraform'

- task: PublishBuildArtifacts@1
  condition: false
  displayName: 'Build Artifact Step'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: AzureWebApp@1
  condition: false
  displayName: 'Azure App Service Deploy: website'
  inputs:
    azureSubscription: 'Resource Manager - DEVOPS'
    appName: 'devops-webapplication-asp'
    package: '$(Build.artifactstagingdirectory)/*.zip'

- task: SonarCloudPrepare@1
  displayName: 'Add SonarCloud Prepare Step'
  inputs:
    SonarCloud: 'SonarCloudServiceConnection'
    organization: 'sreenukoondrapukey'
    scannerMode: 'MSBuild'
    projectKey: 'SreenuKoondrapu_DevOpsWebApplication'
    projectName: 'DevOpsWebApplication'
        
- task: SonarCloudAnalyze@1
  displayName: 'Add SonarCloud Code Analysis Step'
  inputs:
  jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  displayName: 'Add SonarCloud Publish Step'
  inputs:
  pollingTimeoutSec: '300'